lib/ferne_web/router.ex
defmodule FerneWeb.Router do
  use FerneWeb, :router

  import FerneWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {FerneWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  ## Authentication routes

  scope "/", FerneWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/login/:token", UserSessionController, :login
    post "/login/:token", UserSessionController, :post_login
  end

  scope "/", FerneWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    put "/users/delete", UserSettingsController, :delete
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/events/editor", NewEventLive
    get "/events/:id/manage", EventController, :show_manage
    live "/events/:id/manage/organizers", ManageEventOrganizersLive
    get "/events/:id/manage/attendees", EventController, :manage_attendees
    post "/events/:id/cancel", EventController, :cancel
    delete "/events/:id/delete", EventController, :delete
    get "/events/:id/toggle_registrations", EventController, :toggle_registrations
    get "/events/:id/toggle_public", EventController, :toggle_public
    get "/events/:id/activate_block/:block", EventController, :activate_block
    get "/events/:id/special/:block", EventController, :block_special_get
    post "/events/:id/special/:block", EventController, :block_special_post
    get "/events/:id/settings/:block", EventController, :block_get
    post "/events/:id/settings/:block", EventController, :block_post
    delete "/events/:id/delete_block/:block", EventController, :block_delete
    get "/events/:id/save", EventController, :new_template
    post "/events/:id/save", EventController, :create_template
    delete "/events/delete_template/:id", EventController, :delete_template
    get "/events/:id/export_sheet", EventController, :export_sheet
    get "/events/:id/export_party_sheet", EventController, :export_party_sheet
    get "/templates/:id/use", EventController, :new_via_template
    post "/templates/:id/use", EventController, :create_via_template

    get "/teams/new", TeamController, :new
    post "/teams/new", TeamController, :create
    get "/teams/:id/edit", TeamController, :edit
    put "/teams/:id/edit", TeamController, :update
    get "/teams/:id/delete", TeamController, :delete
    live "/teams/:id/members/add", AddTeamMembersLive
    get "/teams/:id/toggle_admin/:user_id", TeamController, :toggle_admin
    get "/teams/:id/toggle_superadmin/:user_id", TeamController, :toggle_superadmin
    get "/teams/:id/remove/:user_id", TeamController, :remove_member
    get "/teams/:id/templates", TeamController, :show_templates
    get "/teams/invite/:token", TeamController, :accept_invite

    get "/teams/:id/attention_lists", AttentionListController, :show
    get "/teams/:id/attention_lists/new", AttentionListController, :new
    post "/teams/:id/attention_lists/new", AttentionListController, :create
    get "/attention_lists/:id/delete", AttentionListController, :delete
  end

  scope "/", FerneWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/frontpage", PageController, :frontpage
    get "/about", PageController, :about
    get "/terms", PageController, :terms
    get "/privacy", PageController, :privacy
    get "/events/:id", EventController, :show_signup
    post "/events/:id", AttendeeController, :create
    get "/edit/:token", AttendeeController, :edit
    put "/edit/:token", AttendeeController, :update
    get "/teams/:id", TeamController, :show
    get "/teams/:id/members", TeamController, :show_members

    # Auth routes
    get "/auth/discord/finish", AuthController, :finish_discord
    get "/auth/discord/:id", AuthController, :start_discord
    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: FerneWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/ferne/groups/team.ex
defmodule Ferne.Team do
  @moduledoc """
  Schema module for teams.
  """
  use Ferne.Schema
  import Ecto.Changeset
  import Ecto.Query
  alias Ferne.{Repo, TeamMember}

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "teams" do
    field :name, :string
    field :description, :string
    field :link, :string
    field :public_members, :boolean

    belongs_to :user, Ferne.User
    has_many :team_members, Ferne.TeamMember, on_delete: :delete_all
    many_to_many :members, Ferne.User, join_through: Ferne.TeamMember
    has_many :events, Ferne.Event, on_delete: :delete_all
    has_many :invites, Ferne.TeamInvite, on_delete: :delete_all
    has_many :templates, Ferne.EventTemplate, on_delete: :delete_all
    has_many :attention_lists, Ferne.AttentionList, on_delete: :delete_all

    timestamps(type: :utc_datetime)
  end

  # Only the team creator can delete the team
  def authorize(:delete_team, %{id: user_id} = _user, %{user_id: user_id} = _team), do: :ok
  def authorize(:delete_team, _user, _team), do: :error

  # Only the team creator or admin can manage the team
  def authorize(:manage_team, %{id: user_id} = _user, %{user_id: user_id} = _team), do: :ok

  def authorize(:manage_team, %{id: user_id} = _user, %{team_members: tms = _team}) do
    entry = Enum.find(tms, &(&1.user_id == user_id))
    if entry && entry.superadmin, do: :ok, else: :error
  end

  def authorize(:manage_team, _user, _team), do: :error
  # Team admins can administrate the team
  def authorize(:administrate_team, %{id: user_id} = _user, %{user_id: user_id} = _team), do: :ok

  def authorize(:administrate_team, %{id: user_id} = _user, %{team_members: members} = _team) do
    found = Enum.find(members, &(&1.user_id == user_id))
    if found && (found.admin || found.superadmin), do: :ok, else: :error
  end

  def authorize(:administrate_team, _user, _team), do: :error
  # Only team members can access the team
  def authorize(:access_team, %{id: user_id} = _user, %{members: members} = _team) do
    if(Enum.find(members, &(&1.id == user_id)), do: :ok, else: :error)
  end

  def authorize(:access_team, _user, _team), do: :error

  def creation_changeset(team, params \\ %{}) do
    team
    |> cast(params, [:name, :description, :link, :public_members])
    |> validate_required([:name, :public_members])
  end

  @doc "Filters a team query by whether the user is a member of the team."
  def by_member(query \\ __MODULE__, user),
    do: from(t in query, select: t, inner_join: m in assoc(t, :members), on: m.id == ^user.id)

  @doc """
  Get a team by its ID.
  """
  def get_by_id(id) do
    case Ecto.UUID.dump(id) do
      {:ok, _} ->
        super(id)

      :error ->
        nil
    end
  end

  @doc """
  Get all teams that a user is part of.
  """
  def get_all_for_user(user) do
    by_member(user)
    |> Repo.all()
  end

  @doc """
  Get all teams that a user is admin or creator of.
  """
  def get_all_for_user_with_admin(user) do
    query =
      from(t in __MODULE__,
        select: t,
        left_join: m in assoc(t, :team_members),
        on: m.user_id == ^user.id,
        where: t.user_id == ^user.id or m.admin or m.superadmin
      )

    Repo.all(query)
  end

  @doc """
  Creates a new team.
  """
  def create(attrs, user) do
    team_changeset =
      %__MODULE__{}
      |> creation_changeset(attrs)
      |> Ecto.Changeset.change(%{user_id: user.id})

    with {:ok, team} <- Repo.insert(team_changeset),
         member_changeset <-
           TeamMember.creation_changeset(%TeamMember{}, %{
             team_id: team.id,
             user_id: user.id,
             admin: true
           }),
         {:ok, _} <- Repo.insert(member_changeset) do
      {:ok, team}
    else
      {:error, err} -> {:error, err}
    end
  end

  @doc """
  Updates a team.
  """
  def update(team, attrs) do
    team
    |> creation_changeset(attrs)
    |> Repo.update()
  end
end

lib/ferne_web/controllers/team_controller.ex
defmodule FerneWeb.TeamController do
  @moduledoc """
  Controller for team routes.
  """
  use FerneWeb, :controller
  alias Ferne.{Team, Event, Repo, EventTemplate, TeamInvite, TeamMember}

  plug :authorize_manage_team
       when action in [
              :edit,
              :update,
              :delete,
              :toggle_admin,
              :toggle_superadmin,
              :remove_member,
              :delete
            ]

  def new(conn, _params) do
    render(conn, "new.html",
      changeset: Team.creation_changeset(%Team{}),
      page_title: "Create new team"
    )
  end

  def create(conn, %{"team" => params}) do
    case Team.create(params, conn.assigns.current_user) do
      {:ok, team} ->
        conn
        |> put_flash(:info, "Your team has been created successfully!")
        |> redirect(to: Routes.team_path(conn, :show, team.id))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "Error while creating team! Please check your inputs.")
        |> render("new.html",
          changeset: changeset,
          page_title: "Create new team"
        )
    end
  end

  def edit(conn, _params) do
    render(conn, "edit.html",
      changeset: Team.creation_changeset(conn.assigns.team),
      page_title: "Edit #{conn.assigns.team.name}"
    )
  end

  def update(conn, %{"team" => params}) do
    if Bodyguard.permit?(Team, :manage_team, conn.assigns.current_user, conn.assigns.team) do
      case Team.update(conn.assigns.team, params) do
        {:ok, team} ->
          conn
          |> put_flash(:info, "Team details updated successfully!")
          |> redirect(to: Routes.team_path(conn, :show, team.id))
  
        {:error, %Ecto.Changeset{} = changeset} ->
          conn
          |> put_flash(:error, "Error while updating team details! Please check your inputs.")
          |> render("edit.html",
            changeset: changeset,
            page_title: "Edit #{conn.assigns.team.name}"
          )
      end
    end
  end

  def show(conn, %{"id" => id}) do
    team = Team.get_by_id(id) |> Ferne.Repo.preload([:members, :team_members])

    if team do
      events =
        if Bodyguard.permit?(Team, :access_team, conn.assigns.current_user, team),
          do: Event.by_team(team) |> Repo.all(),
          else: Event.by_team(team) |> Event.by_public() |> Repo.all()

      render(conn, "show.html", team: team, public_events: events, page_title: team.name)
    else
      conn
      |> put_view(FerneWeb.ErrorView)
      |> render("404.html")
    end
  end

  def show_members(conn, %{"id" => id}) do
    team = Team.get_by_id(id) |> Ferne.Repo.preload([:members, :team_members])

    if team.public_members ||
         Bodyguard.permit?(Team, :access_team, conn.assigns.current_user, team) do
      render(conn, "show_members.html", team: team, page_title: "Members of #{team.name}")
    else
      conn
      |> put_flash(:error, "You're not authorized to do that.")
      |> redirect(to: Routes.team_path(conn, :show, id))
    end
  end

  def show_templates(conn, %{"id" => id}) do
    team = Team.get_by_id(id) |> Ferne.Repo.preload([:members, :team_members])
    templates = EventTemplate.by_team(team) |> Ferne.Repo.all()

    render(conn, "show_templates.html",
      templates: templates,
      team: team,
      page_title: "Templates of #{team.name}"
    )
  end

  def accept_invite(conn, %{"token" => token}) do
    case TeamInvite.confirm(token, conn.assigns.current_user) do
      {:ok, team} ->
        conn
        |> put_flash(:info, "You've been added to #{team.name}!")
        |> redirect(to: Routes.team_path(conn, :show, team.id))

      :error ->
        conn
        |> put_flash(:error, "Something went wrong when trying to accept this invite.")
        |> redirect(to: Routes.page_path(conn, :index))
    end
  end

  def toggle_admin(conn, %{"user_id" => user_id}) do
    tm = TeamMember.get_for_team_and_user(conn.assigns.team, %{id: user_id})

    if Bodyguard.permit?(Team, :manage_team, conn.assigns.current_user, conn.assigns.team) do
      changeset = TeamMember.edit_admin_changeset(tm, %{admin: !tm.admin})
      Ferne.Repo.update(changeset)
    end

    conn
    |> redirect(to: Routes.team_path(conn, :show_members, conn.assigns.team.id))
  end

  def toggle_superadmin(conn, %{"user_id" => user_id}) do
    tm = TeamMember.get_for_team_and_user(conn.assigns.team, %{id: user_id})

    if Bodyguard.permit?(Team, :manage_team, conn.assigns.current_user, conn.assigns.team) do
      changeset = TeamMember.edit_superadmin_changeset(tm, %{superadmin: !tm.superadmin})
      Ferne.Repo.update(changeset)
    end

    conn
    |> redirect(to: Routes.team_path(conn, :show_members, conn.assigns.team.id))
  end

  def remove_member(conn, %{"user_id" => user_id}) do
    tm = TeamMember.get_for_team_and_user(conn.assigns.team, %{id: user_id})

    if Bodyguard.permit?(Team, :manage_team, conn.assigns.current_user, conn.assigns.team) do
      Ferne.Repo.delete(tm)
    end

    conn
    |> put_flash(:info, "Team member removed.")
    |> redirect(to: Routes.team_path(conn, :show_members, conn.assigns.team.id))
  end

  def delete(conn, _params) do
    if Bodyguard.permit?(Team, :delete_team, conn.assigns.current_user, conn.assigns.team) do
      Team.delete(conn.assigns.team)
    end

    conn
    |> redirect(to: Routes.page_path(conn, :index))
  end

  def authorize_manage_team(conn, _opts) do
    team = Team.get_by_id(conn.path_params["id"]) |> Repo.preload([:team_members])

    if Bodyguard.permit?(Team, :manage_team, conn.assigns.current_user, team) do
      conn
      |> assign(:team, team)
    else
      conn
      |> put_flash(:error, "You're not authorized to do that.")
      |> redirect(to: Routes.page_path(conn, :index))
    end
  end
end

lib/ferne_web/views/team_view.ex
defmodule FerneWeb.TeamView do
  @moduledoc """
  View module for teams.
  """
  use FerneWeb, :view

  def pair_team_members(team) do
    Enum.map(team.members, fn member ->
      join_struct = Enum.find(team.team_members, &(&1.user_id == member.id))
      {member, join_struct}
    end)
  end
end

lib/ferne_web/templates/team/_form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <fieldset class="mb-3">
    <%= label f, :name, class: "form-label form-label-required" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </fieldset>

  <fieldset class="mb-3">
    <%= label f, :description, class: "form-label" %>
    <%= textarea f, :description, class: "form-control", placeholder: "A short description of what your team is about..." %>
    <%= error_tag f, :description %>
  </fieldset>

  <fieldset class="mb-3">
    <%= label f, :link, "URL", class: "form-label" %>
    <%= url_input f, :link, class: "form-control" %>
    <%= error_tag f, :link %>
  </fieldset>

  <fieldset class="mb-3">
    <div class="form-check">
      <%= checkbox f, :public_members, class: "form-check-input" %>
      <%= label f, :public_members, "Show team members publicly?", class: "form-check-label" %>
    </div>
  </fieldset>


  <small class="d-block mb-2 text-muted"><span class="required-star">*</span> = required field</small>
  <div>
    <%= submit @submit_text, class: "btn btn-primary" %>
  </div>
</.form>

lib/ferne_web/templates/team/show_members.html.heex
<%= render("_about.html", Map.merge(assigns, %{active: :members})) %>

<div class="mw-lg-xl m-auto">
  <%= if Bodyguard.permit?(Ferne.Team, :manage_team, @current_user, @team) do %>
    <div class="text-end">
      <%= link to: Routes.live_path(@conn, FerneWeb.AddTeamMembersLive, @team.id) do %>
        <button class="btn btn-primary">
          <i class="bi bi-person-plus-fill"></i> Invite 
        </button>
      <% end %>
    </div>
    <div class="text-muted mx-3 my-2">
      Psst: There's three team permission levels!
      The <strong>creator</strong> can do everything. Team <strong>admins</strong>
      can do everything the creator can do, with exception of deleting the team.
      Team <strong>organizers</strong> have <i>write</i> access to all events organized
      by the team. Team <strong>members</strong> have <i>read</i> access to all events
      organized by the team.
    </div>
  <% end %>
  <ul class="list-group list-group-flush">
    <%= for {member, tm} <- pair_team_members(@team) do %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div>
          <h5 class="fw-bold mb-0"><%= member.name %></h5>
          <div>@<%= member.username %></div>
        </div>
        <div>
          <%= if Bodyguard.permit?(Ferne.Team, :manage_team, @current_user, @team) do %>
            <%= if member.id == @team.user_id do %>
              Creator
            <% else %>
              <%= link if(tm.superadmin, do: "Remove Admin", else: "Make Admin"), to: Routes.team_path(@conn, :toggle_superadmin, @team.id, member.id), class: "btn btn-outline-primary" %>
              <%= link if(tm.admin, do: "Remove Organizer", else: "Make Organizer"), to: Routes.team_path(@conn, :toggle_admin, @team.id, member.id), class: "btn btn-outline-primary" %>
              <%= link "Remove", to: Routes.team_path(@conn, :remove_member, @team.id, member.id), class: "btn btn-danger" %>
            <% end %>
          <% else %>
            <%= cond do %>
              <% member.id == @team.user_id -> %>
                Creator
              <% tm.superadmin -> %>
                Admin
              <% tm.admin -> %>
                Organizer
              <% true -> %>
                Member
            <% end %>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

lib/ferne_web/templates/team/show_templates.html.heex
<%= render("_about.html", Map.merge(assigns, %{active: :templates})) %>

<div class="mw-lg-xl m-auto">
  <%= if length(@templates) == 0 do %>
    <div class="text-muted text-center p-5 bg-light rounded">
      No templates yet! You can create one from the event management page.
    </div>
  <% end %>
  <%= for template <- @templates do %>
    <div class="border rounded p-3 mb-2 d-flex flex-column flex-lg-row align-items-center">
      <div>
        <h4 class="m-0 fw-bold me-2"><%= template.name %></h4>
        <div class="text-muted"><strong><%= length(Map.keys(template.block_data)) %></strong> blocks active</div>
      </div>
      <div class="ms-auto">
        <%= link "Create event from template", to: Routes.event_path(@conn, :new_via_template, template.id), class: "btn btn-primary" %>
      </div>
      <%= if Bodyguard.permit?(Ferne.Team, :administrate_team, @current_user, @team) do %>
        <%= link to: Routes.event_path(@conn, :delete_template, template.id), method: :delete, class: "btn btn-danger ms-1" do %>
          <i class="bi bi-trash"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>